// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-extend/fba583daa3584e737f9c45b2428bfe3eca448b11/index.d.ts
declare module 'extend' {

function extend<T extends Object>(deep: boolean, target: T, ...objects: Object[]): T;
function extend<T extends Object>(target: T, ...objects: Object[]): T;

export = extend;
}
